# Claude MPM Configuration
# Consolidated configuration file for all Claude MPM settings

# Terminal wrapper settings
terminal:
  # Terminal debug logging - set to true to enable verbose logging
  debug_logging: true
  
  # PTY process creation settings
  # Disable preexec_fn if having issues with process creation
  use_preexec_fn: false
  
  # Retry without preexec_fn if it fails
  retry_without_preexec: true

# Project configuration
project:
  version: "1.0"
  project_name: "claude-mpm"
  agents:
    enabled: true
  tickets:
    auto_create: true
    prefix: "TSK"

# Hook configuration
hooks:
  version: "1.0"
  session_response_logger:
    enabled: true
    module: "claude_mpm.hooks.builtin.session_response_logger_hook"
    config:
      enabled: true
      log_all_agents: true
      excluded_agents: []
      min_response_length: 50
  response_tracking:
    enabled: false
    module: "claude_mpm.hooks.response_tracking_hook"
    config:
      enabled: false

# Response tracking configuration  
response_tracking:
  enabled: true
  base_dir: .claude-mpm/responses/
  track_all: true
  excluded_agents: []
  storage:
    auto_cleanup_days: 30
  metadata_tracking:
    track_tokens: true
    track_duration: true
    track_tools: true
    track_confidence: true
    track_model: true

# Session management configuration
sessions:
  # Use session-specific logging to prevent file contention
  use_session_specific_logs: true
  base_dir: .claude-mpm/sessions/
  # Clean up old session files after X days
  auto_cleanup_days: 7
  # Session log format
  log_format: "{session_id}_{timestamp}.log"

# Response logging configuration (for async session logger)
response_logging:
  # Enable response logging
  enabled: true
  
  # Use async logging for better performance
  use_async: true
  
  # Logging format: json, syslog, or journald
  format: json
  
  # Directory to store session responses
  session_directory: ".claude-mpm/responses"
  
  # Timestamp format for filenames
  timestamp_format: "{agent}_{timestamp}"
  
  # Force synchronous mode for debugging (overrides use_async)
  debug_sync: false
  
  # Maximum queue size for async writes
  max_queue_size: 10000
  
  # Enable compression for JSON logs (reduces disk usage)
  enable_compression: false