"""Migration 6.5.41: Remove stale .claude-mpm/PM_INSTRUCTIONS.md cache files.

WHAT: Deletes leftover auto-generated .claude-mpm/PM_INSTRUCTIONS.md launcher
cache files (project- and user-level) while preserving user-override files.

WHY: Issue #794 renamed the auto-generated launcher cache from
.claude-mpm/PM_INSTRUCTIONS.md to .claude-mpm/PM_INSTRUCTIONS_CACHE.md.
Existing installs retain the old PM_INSTRUCTIONS.md file indefinitely. That
filename is ALSO the legitimate user-override input, so it cannot be deleted
blindly — doing so would destroy a user's hand-authored overrides (issue #796).

SAFETY:
- Only deletes a file when it contains the auto-generated banner (BANNER_DEPLOYED)
  near the top — that proves it is a generated cache, not a user override.
- Files WITHOUT the banner are user overrides and are preserved untouched.
- Reads only the first ~10 lines for the banner check (no whole-file reads).
- Non-fatal: logs errors and continues.
- Idempotent: safe to run multiple times.

References
----------
SPEC-INTEGRATIONS-09~1 : docs/specs/integrations.md#SPEC-INTEGRATIONS-09~1
"""

import logging
from pathlib import Path

from claude_mpm.constants import BANNER_DEPLOYED

logger = logging.getLogger(__name__)

# The auto-generated banner string identifying a generated cache file. We match
# on the leading sentinel rather than the whole multi-line banner so that minor
# trailing-text drift across versions does not defeat detection.
AUTOGEN_BANNER = "<!-- AUTO-GENERATED by claude-mpm — DO NOT EDIT."

# Number of leading lines scanned for the banner. The banner is always at the
# very top of a generated file; scanning a small window avoids reading large
# user-authored override files in full.
_BANNER_SCAN_LINES = 10


def _is_autogenerated_cache(path: Path) -> bool:
    """Return True if the file's first lines contain the auto-generated banner.

    WHAT: Reads up to the first ~10 lines of ``path`` and reports whether the
    auto-generated cache banner appears in that window.
    WHY: The same filename (PM_INSTRUCTIONS.md) is used for BOTH the generated
    cache output and the user-override input; only the banner distinguishes a
    safe-to-delete cache from a user override that must be preserved.

    :spec: SPEC-INTEGRATIONS-09~1
    """
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            head = "".join(next(fh, "") for _ in range(_BANNER_SCAN_LINES))
    except OSError as exc:
        # If we cannot read it, err on the side of preservation.
        logger.warning("Cannot read %s, treating as user override: %s", path, exc)
        return False
    return AUTOGEN_BANNER in head or BANNER_DEPLOYED in head


def _candidate_files() -> list[Path]:
    """Return the set of PM_INSTRUCTIONS.md paths this migration may clean.

    WHAT: Collects the current-project and user-level
    ``.claude-mpm/PM_INSTRUCTIONS.md`` paths.
    WHY: The stale cache can exist both in the project being worked on
    (Path.cwd()) and at the user level (~/.claude-mpm/); other migrations in
    this package operate per-project on startup, so each project is cleaned the
    next time claude-mpm runs in it.

    :spec: SPEC-INTEGRATIONS-09~1
    """
    candidates = [
        Path.cwd() / ".claude-mpm" / "PM_INSTRUCTIONS.md",
        Path.home() / ".claude-mpm" / "PM_INSTRUCTIONS.md",
    ]
    # De-duplicate while preserving order (cwd could equal home in edge cases).
    seen: set[Path] = set()
    unique: list[Path] = []
    for path in candidates:
        resolved = path.resolve()
        if resolved not in seen:
            seen.add(resolved)
            unique.append(path)
    return unique


def run_migration() -> bool:
    """Delete stale auto-generated PM_INSTRUCTIONS.md cache files, keep overrides.

    WHAT: For each candidate ``.claude-mpm/PM_INSTRUCTIONS.md``, deletes it only
    when it carries the auto-generated banner; user-override files (no banner)
    are preserved and logged as such.
    WHY: The cache was renamed to PM_INSTRUCTIONS_CACHE.md in #794, but the old
    filename doubles as the user-override input — so removal must be banner-gated
    to avoid destroying user content (issue #796).
    Test: Create banner-bearing and banner-less PM_INSTRUCTIONS.md files; run the
    migration; assert the banner file is gone and the override file remains.

    :spec: SPEC-INTEGRATIONS-09~1
    """
    try:
        any_error = False
        removed = 0
        preserved = 0

        for path in _candidate_files():
            if not path.exists():
                logger.debug("No file at %s, nothing to do", path)
                continue

            if not _is_autogenerated_cache(path):
                preserved += 1
                logger.info("Preserved (user override): %s", path)
                continue

            try:
                path.unlink()
                removed += 1
                logger.info("Removed stale auto-generated PM cache: %s", path)
            except OSError as exc:
                logger.error("Failed to remove %s: %s", path, exc)
                any_error = True

        logger.info(
            "Migration complete: removed=%d cache file(s), preserved=%d override(s), errors=%s",
            removed,
            preserved,
            any_error,
        )
        return not any_error

    except Exception as exc:
        logger.error("Unexpected error in remove_stale_pm_instructions_cache: %s", exc)
        return False
