# Dependabot configuration for automated dependency updates
# This helps keep GitHub Actions and Python dependencies up to date

version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Only update direct dependencies
    allow:
      - dependency-type: "direct"
    # Group documentation dependencies together
    groups:
      documentation:
        patterns:
          - "sphinx*"
          - "autodoc*"
          - "myst-parser"
          - "recommonmark"
