name: claude-mpm
channels:
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.11
  
  # Core packages that benefit from conda compilation
  - pyyaml>=6.0
  - psutil>=5.9.0
  - watchdog>=3.0.0
  - aiohttp>=3.9.0
  - websockets>=12.0
  - pandas>=2.1.0
  
  # Development tools
  - pytest>=7.0
  - pytest-asyncio
  - pytest-cov
  - black>=23.0.0
  - mypy>=1.0.0
  - ruff>=0.1.0
  - pylint>=3.0.0
  
  # Build tools
  - pip
  - setuptools>=61.0
  - wheel
  
  # Documentation tools (optional, comment out if not needed)
  - sphinx>=7.2.0
  
  # Pip dependencies for packages not in conda or for editable install
  - pip:
    # Install claude-mpm in editable mode with all extras
    - -e .[dev,agents]
    
    # Additional pip-only dependencies
    - ai-trackdown-pytools>=1.4.0
    - python-dotenv>=0.19.0
    - click>=8.0.0
    - pexpect>=4.8.0
    - requests>=2.25.0
    
    # Flask and extensions
    - flask>=3.0.0
    - flask-cors>=4.0.0
    
    # SocketIO and async
    - python-socketio>=5.11.0
    - aiohttp-cors>=0.7.0
    - python-engineio>=4.8.0
    - aiofiles>=23.0.0
    
    # Content processing
    - python-frontmatter>=1.0.0
    - mistune>=3.0.0
    - ijson>=3.2.0
    
    # MCP support
    - mcp>=0.1.0
    
    # Utilities
    - toml>=0.10.2
    - packaging>=21.0
    - pydantic>=2.0.0
    - pydantic-settings>=2.0.0
    - pyee>=13.0.0
    
    # Type stubs
    - types-PyYAML>=6.0.0
    - types-requests>=2.25.0
    
    # Development tools not in conda
    - flake8
    - flake8-import-order
    - flake8-tidy-imports
    - flake8-bugbear
    - pre-commit
    
    # Tree-sitter and language parsers
    - tree-sitter>=0.21.0
    - tree-sitter-python>=0.21.0
    - tree-sitter-javascript>=0.21.0
    - tree-sitter-typescript>=0.21.0
    - tree-sitter-go>=0.21.0
    - tree-sitter-rust>=0.21.0
    - tree-sitter-java>=0.21.0
    - tree-sitter-cpp>=0.21.0
    - tree-sitter-c>=0.21.0
    - tree-sitter-ruby>=0.21.0
    - tree-sitter-php>=0.21.0

# Environment variables
variables:
  DISABLE_TELEMETRY: "1"
  CLAUDE_MPM_DEV_ENV: "mamba"