# Ruff configuration for claude-mpm
# Fast Python linter with comprehensive checks

# Same line length as Black
line-length = 88

# Target Python 3.8+
target-version = "py38"

# Enable specific rule sets
select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # pyflakes
    "I",      # isort
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "UP",     # pyupgrade
    "ARG",    # flake8-unused-arguments
    "PTH",    # flake8-use-pathlib
    "SIM",    # flake8-simplify
    "TID",    # flake8-tidy-imports
    "RET",    # flake8-return
    "FBT",    # flake8-boolean-trap
    "RUF",    # Ruff-specific rules
    "PL",     # Pylint
    "NPY",    # NumPy-specific rules
    "PERF",   # Performance linting
]

# Ignore specific rules
ignore = [
    "E501",   # Line too long (handled by Black)
    "E203",   # Whitespace before ':' (conflicts with Black)
    "W503",   # Line break before binary operator (conflicts with Black)
    "B008",   # Do not perform function calls in argument defaults
    "B024",   # Abstract base class without abstract methods
    "UP007",  # Use X | Y for type hints (not compatible with Python 3.8)
    "SIM108", # Use ternary operator (sometimes less readable)
    "RET504", # Unnecessary variable assignment before return
    "FBT001", # Boolean positional arg in function definition
    "FBT002", # Boolean default value in function definition
    "PLR0913", # Too many arguments to function call
    "PLR2004", # Magic value used in comparison
]

# Exclude directories from linting
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".venv-*",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "dashboard_*",
    "realtime_*",
    "test_screenshots",
]

# Allow autofix for all enabled rules
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[per-file-ignores]
# Allow unused imports in __init__ files
"__init__.py" = ["F401", "F403"]
# Allow print statements and other test-specific patterns in tests
"tests/**/*.py" = ["S101", "ARG001", "PLR2004", "PLR0913"]
# Allow complex scripts
"scripts/*.py" = ["PLR0912", "PLR0915", "C901"]

[isort]
# Use Black-compatible import sorting
profile = "black"
known-first-party = ["claude_mpm"]

[mccabe]
# Maximum complexity
max-complexity = 10

[pydocstyle]
# Use Google-style docstrings
convention = "google"