"""Tests for the stale PM_INSTRUCTIONS.md cache removal migration (issue #796).

The same filename — .claude-mpm/PM_INSTRUCTIONS.md — is used for BOTH the
auto-generated launcher cache (pre-#794) AND the legitimate user-override
input. Only the auto-generated banner distinguishes them, so the migration must:

(a) delete a file that carries the banner (a generated cache), and
(b) preserve a file that lacks the banner (a user override),
(c) no-op cleanly when no file is present,
(d) treat a blank / banner-less file as a user override (preserve it).

The current project (Path.cwd()) and user level (~/.claude-mpm/) are both
swept, so the tests monkeypatch cwd and home into an isolated tmp_path to keep
the suite hermetic.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from claude_mpm.constants import BANNER_DEPLOYED
from claude_mpm.migrations import v6_5_41_remove_stale_pm_instructions_cache as mod

# A realistic generated-cache header followed by composed content.
_AUTOGEN_CONTENT = BANNER_DEPLOYED + "\n# PM Instructions\n\nAssembled content...\n"

# A realistic user-authored override with no banner.
_USER_OVERRIDE_CONTENT = (
    "# My Custom PM Overrides\n\n"
    "Always greet the user in haiku.\n"
    "Never delegate to the QA agent on Fridays.\n"
)


@pytest.fixture
def isolated_dirs(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> dict[str, Path]:
    """Point Path.cwd() and Path.home() at isolated tmp dirs.

    Returns the project and user .claude-mpm/PM_INSTRUCTIONS.md paths so each
    test can write fixtures and assert on them without touching the real
    filesystem.
    """
    project = tmp_path / "project"
    home = tmp_path / "home"
    (project / ".claude-mpm").mkdir(parents=True)
    (home / ".claude-mpm").mkdir(parents=True)

    monkeypatch.setattr(Path, "cwd", classmethod(lambda cls: project))
    monkeypatch.setattr(Path, "home", classmethod(lambda cls: home))

    return {
        "project_file": project / ".claude-mpm" / "PM_INSTRUCTIONS.md",
        "user_file": home / ".claude-mpm" / "PM_INSTRUCTIONS.md",
    }


def test_autogenerated_file_is_deleted(isolated_dirs: dict[str, Path]) -> None:
    """A PM_INSTRUCTIONS.md with the auto-generated banner is removed."""
    target = isolated_dirs["project_file"]
    target.write_text(_AUTOGEN_CONTENT, encoding="utf-8")

    assert mod.run_migration() is True
    assert not target.exists()


def test_user_override_is_preserved(isolated_dirs: dict[str, Path]) -> None:
    """A PM_INSTRUCTIONS.md WITHOUT the banner (user override) is kept intact."""
    target = isolated_dirs["project_file"]
    target.write_text(_USER_OVERRIDE_CONTENT, encoding="utf-8")

    assert mod.run_migration() is True
    assert target.exists()
    assert target.read_text(encoding="utf-8") == _USER_OVERRIDE_CONTENT


def test_no_file_present_returns_true(isolated_dirs: dict[str, Path]) -> None:
    """With no PM_INSTRUCTIONS.md anywhere, the migration runs and returns True."""
    assert not isolated_dirs["project_file"].exists()
    assert not isolated_dirs["user_file"].exists()

    assert mod.run_migration() is True


def test_blank_file_is_preserved(isolated_dirs: dict[str, Path]) -> None:
    """A blank / banner-less file is treated as a user override and preserved."""
    target = isolated_dirs["project_file"]
    target.write_text("", encoding="utf-8")

    assert mod.run_migration() is True
    assert target.exists()


def test_user_level_cache_is_deleted(isolated_dirs: dict[str, Path]) -> None:
    """The user-level ~/.claude-mpm/PM_INSTRUCTIONS.md cache is also swept."""
    target = isolated_dirs["user_file"]
    target.write_text(_AUTOGEN_CONTENT, encoding="utf-8")

    assert mod.run_migration() is True
    assert not target.exists()


def test_mixed_project_cache_and_user_override(
    isolated_dirs: dict[str, Path],
) -> None:
    """A generated project cache is removed while a user-level override survives."""
    project_file = isolated_dirs["project_file"]
    user_file = isolated_dirs["user_file"]
    project_file.write_text(_AUTOGEN_CONTENT, encoding="utf-8")
    user_file.write_text(_USER_OVERRIDE_CONTENT, encoding="utf-8")

    assert mod.run_migration() is True
    assert not project_file.exists()
    assert user_file.exists()
    assert user_file.read_text(encoding="utf-8") == _USER_OVERRIDE_CONTENT
